import glob
from pathlib import Path


def main() -> int:
    lib_dirs = sorted(glob.glob("/usr/local/lib/python3.12/dist-packages/nvidia/*/lib"))
    env_file = Path("/content/vllm_env.sh")

    lines = [
        "#!/usr/bin/env bash",
        "# Generated by deploy.sh. Source this before running vllm in console.",
    ]
    if lib_dirs:
        joined = ":".join(lib_dirs)
        lines.append(f'export LD_LIBRARY_PATH="{joined}:$LD_LIBRARY_PATH"')
    else:
        lines.append("# No NVIDIA lib dirs found at generation time.")

    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    env_file.chmod(0o755)

    print(f"ENV_FILE={env_file}")
    if lib_dirs:
        print(f"ENV_LIB_DIRS={len(lib_dirs)}")
        print("ENV_READY=1")
    else:
        print("ENV_READY=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
